# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Screen01.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(910, 977)
        Form.setAccessibleDescription("")
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: white;")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 20, 451, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("texisle.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Tex_isle_processing = QtWidgets.QLabel(Form)
        self.Tex_isle_processing.setGeometry(QtCore.QRect(260, 130, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        self.Tex_isle_processing.setFont(font)
        self.Tex_isle_processing.setAlignment(QtCore.Qt.AlignCenter)
        self.Tex_isle_processing.setObjectName("Tex_isle_processing")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(260, 180, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(350, 250, 171, 21))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(330, 290, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(370, 280, 181, 31))
        self.textEdit.setObjectName("textEdit")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(580, 330, 171, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItems(["Tex-Isle,Inc."]);

        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(126, 330, 131, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(260, 330, 171, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(500, 330, 81, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 370, 171, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(260, 410, 171, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(184, 451, 71, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(260, 450, 111, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItems(["43147"]);
        
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(390, 450, 121, 16))
        self.label_8.setObjectName("label_8")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(480, 450, 111, 21))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItems(["43243"]);

        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(620, 450, 81, 16))
        self.label_9.setObjectName("label_9")
        self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(680, 450, 111, 21))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItems(["TIP00301"]);

        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(225, 500, 21, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(260, 500, 81, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(365, 500, 31, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(400, 500, 81, 22))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(560, 500, 81, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(Form)
        self.lineEdit_7.setGeometry(QtCore.QRect(710, 500, 81, 22))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(670, 500, 31, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(500, 500, 61, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(206, 550, 51, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_8 = QtWidgets.QLineEdit(Form)
        self.lineEdit_8.setGeometry(QtCore.QRect(260, 550, 121, 22))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(400, 550, 91, 16))
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setObjectName("label_15")
        self.lineEdit_9 = QtWidgets.QLineEdit(Form)
        self.lineEdit_9.setGeometry(QtCore.QRect(480, 550, 121, 22))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(620, 550, 71, 16))
        self.label_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_16.setObjectName("label_16")
        self.lineEdit_10 = QtWidgets.QLineEdit(Form)
        self.lineEdit_10.setGeometry(QtCore.QRect(690, 550, 101, 22))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(260, 610, 391, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(170, 670, 51, 16))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(340, 660, 71, 31))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(470, 660, 71, 31))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(600, 670, 51, 16))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(Form)
        self.label_22.setGeometry(QtCore.QRect(710, 670, 51, 20))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.lineEdit_11 = QtWidgets.QLineEdit(Form)
        self.lineEdit_11.setGeometry(QtCore.QRect(140, 700, 113, 22))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(Form)
        self.lineEdit_12.setGeometry(QtCore.QRect(140, 750, 113, 22))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(Form)
        self.lineEdit_13.setGeometry(QtCore.QRect(140, 800, 113, 22))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(Form)
        self.lineEdit_14.setGeometry(QtCore.QRect(140, 850, 113, 22))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(Form)
        self.lineEdit_15.setGeometry(QtCore.QRect(140, 900, 113, 22))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(270, 700, 49, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(270, 750, 49, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(Form)
        self.label_25.setGeometry(QtCore.QRect(270, 800, 49, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(Form)
        self.label_26.setGeometry(QtCore.QRect(270, 850, 49, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(Form)
        self.label_27.setGeometry(QtCore.QRect(270, 900, 49, 16))
        self.label_27.setObjectName("label_27")
        self.lineEdit_16 = QtWidgets.QLineEdit(Form)
        self.lineEdit_16.setGeometry(QtCore.QRect(310, 750, 113, 22))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(Form)
        self.lineEdit_17.setGeometry(QtCore.QRect(310, 700, 113, 22))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(Form)
        self.lineEdit_18.setGeometry(QtCore.QRect(310, 850, 113, 22))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(Form)
        self.lineEdit_19.setGeometry(QtCore.QRect(310, 800, 113, 22))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(Form)
        self.lineEdit_20.setGeometry(QtCore.QRect(310, 900, 113, 22))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(Form)
        self.lineEdit_21.setGeometry(QtCore.QRect(450, 900, 113, 22))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(Form)
        self.lineEdit_22.setGeometry(QtCore.QRect(450, 800, 113, 22))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(Form)
        self.lineEdit_23.setGeometry(QtCore.QRect(450, 750, 113, 22))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(Form)
        self.lineEdit_24.setGeometry(QtCore.QRect(450, 700, 113, 22))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(Form)
        self.lineEdit_25.setGeometry(QtCore.QRect(450, 850, 113, 22))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(Form)
        self.lineEdit_26.setGeometry(QtCore.QRect(590, 900, 71, 22))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(Form)
        self.lineEdit_27.setGeometry(QtCore.QRect(590, 800, 71, 22))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(Form)
        self.lineEdit_28.setGeometry(QtCore.QRect(590, 750, 71, 22))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(Form)
        self.lineEdit_29.setGeometry(QtCore.QRect(590, 700, 71, 22))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(Form)
        self.lineEdit_30.setGeometry(QtCore.QRect(590, 850, 71, 22))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(Form)
        self.lineEdit_31.setGeometry(QtCore.QRect(710, 850, 61, 22))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(Form)
        self.lineEdit_32.setGeometry(QtCore.QRect(710, 750, 61, 22))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(Form)
        self.lineEdit_33.setGeometry(QtCore.QRect(710, 800, 61, 22))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(Form)
        self.lineEdit_34.setGeometry(QtCore.QRect(710, 900, 61, 22))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(Form)
        self.lineEdit_35.setGeometry(QtCore.QRect(710, 700, 61, 22))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.label_28 = QtWidgets.QLabel(Form)
        self.label_28.setGeometry(QtCore.QRect(190, 940, 121, 16))
        self.label_28.setObjectName("label_28")
        self.lineEdit_36 = QtWidgets.QLineEdit(Form)
        self.lineEdit_36.setGeometry(QtCore.QRect(710, 940, 61, 22))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_37 = QtWidgets.QLineEdit(Form)
        self.lineEdit_37.setGeometry(QtCore.QRect(310, 940, 113, 22))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtWidgets.QLineEdit(Form)
        self.lineEdit_38.setGeometry(QtCore.QRect(450, 940, 113, 22))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(Form)
        self.lineEdit_39.setGeometry(QtCore.QRect(590, 940, 71, 22))
        self.lineEdit_39.setObjectName("lineEdit_39")

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(600, 280, 75, 24))
        self.pushButton.setObjectName("pushButton")
        
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.textEdit.raise_()
        self.label_5.raise_()
        self.lineEdit.raise_()
        self.label_6.raise_()
        self.comboBox.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.label_7.raise_()
        self.comboBox_2.raise_()
        self.label_8.raise_()
        self.comboBox_3.raise_()
        self.label_9.raise_()
        self.comboBox_4.raise_()
        self.label_10.raise_()
        self.lineEdit_4.raise_()
        self.label_11.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_7.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.lineEdit_6.raise_()
        self.label_14.raise_()
        self.lineEdit_8.raise_()
        self.label_15.raise_()
        self.lineEdit_9.raise_()
        self.label_16.raise_()
        self.lineEdit_10.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.lineEdit_11.raise_()
        self.lineEdit_12.raise_()
        self.lineEdit_13.raise_()
        self.lineEdit_14.raise_()
        self.lineEdit_15.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.lineEdit_16.raise_()
        self.lineEdit_17.raise_()
        self.lineEdit_18.raise_()
        self.lineEdit_19.raise_()
        self.lineEdit_20.raise_()
        self.lineEdit_21.raise_()
        self.lineEdit_22.raise_()
        self.lineEdit_23.raise_()
        self.lineEdit_24.raise_()
        self.lineEdit_25.raise_()
        self.lineEdit_26.raise_()
        self.lineEdit_27.raise_()
        self.lineEdit_28.raise_()
        self.lineEdit_29.raise_()
        self.lineEdit_30.raise_()
        self.lineEdit_31.raise_()
        self.lineEdit_32.raise_()
        self.lineEdit_33.raise_()
        self.lineEdit_34.raise_()
        self.lineEdit_35.raise_()
        self.label_28.raise_()
        self.lineEdit_36.raise_()
        self.lineEdit_37.raise_()
        self.lineEdit_38.raise_()
        self.lineEdit_39.raise_()
        self.Tex_isle_processing.raise_()
        self.pushButton.raise_()
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Tex_isle_processing.setText(_translate("Form", "Tex-Isle Processing"))
        self.label_2.setText(_translate("Form", "Lab/Hydro Released Lots"))
        self.label_3.setText(_translate("Form", "Robstown, TX"))
        self.label_4.setText(_translate("Form", "Date:"))
        self.label_5.setText(_translate("Form", "TDS Transaction #(s):"))
        self.label_6.setText(_translate("Form", "Customer:"))
        self.label_7.setText(_translate("Form", "GT Pipe PO:"))
        self.label_8.setText(_translate("Form", "Process Order #"))
        self.label_9.setText(_translate("Form", "WO#(TIP)"))
        self.label_10.setText(_translate("Form", "OD:"))
        self.label_11.setText(_translate("Form", "Wall:"))
        self.label_12.setText(_translate("Form", "Grade:"))
        self.label_13.setText(_translate("Form", "Weight/ft:"))
        self.label_14.setText(_translate("Form", "Design:"))
        self.label_15.setText(_translate("Form", "Manufacturer:"))
        self.label_16.setText(_translate("Form", "Avg Length:"))
        self.label_17.setText(_translate("Form", "Total for Lab/Hydro Released Lots"))
        self.label_18.setText(_translate("Form", "Lot#"))
        self.label_19.setText(_translate("Form", "Qty UV Coated"))
        self.label_20.setText(_translate("Form", "Qty No UV Coated"))
        self.label_21.setText(_translate("Form", "Feet"))
        self.label_22.setText(_translate("Form", "Tons"))
        self.label_23.setText(_translate("Form", "Prime"))
        self.label_24.setText(_translate("Form", "Prime"))
        self.label_25.setText(_translate("Form", "Prime"))
        self.label_26.setText(_translate("Form", "Prime"))
        self.label_27.setText(_translate("Form", "Prime"))
        self.label_28.setText(_translate("Form", "Total Released Moved"))
        self.pushButton.setText(_translate("Form", "UpdateForm"))

